first commit
wolox-training/tr-react pull request #1
Opened 2018-08-06 14:59 UTC by tsregit

-Initial commit with content layout
-Add css and Images.
-Add animation on div.

2018-08-06 16:15 UTC, arconejeros commented on scss/titles.scss
> +  margin-left: -100px;
avoid using negative margins

2018-08-06 16:15 UTC, arconejeros commented on scss/titles.scss
> +  margin-left: -31px;
Same here

2018-08-06 16:35 UTC, arconejeros commented on index.html
> +          <br>
`<br>` tags shouldn't be used to make gaps between elements, instead adjust the margin styled by CSS

2018-08-08 17:52 UTC, gon-escalante commented
add a screenshot in the PR as a reference, it helps a lot

2018-08-08 18:01 UTC, gon-escalante requested changes

2018-08-08 18:01 UTC, gon-escalante commented on scss/tech.scss
> +  border-radius: 5px 5px 5px 5px;
`border-radius: 5px;`
it applies to all 4 borders by default

2018-08-08 18:01 UTC, gon-escalante commented on scss/tech.scss
> +  -moz-border-radius: 5px 5px 5px 5px;
same

2018-08-08 18:01 UTC, gon-escalante commented on scss/tech.scss
> +  -webkit-border-radius: 5px 5px 5px 5px;
same

2018-08-08 19:23 UTC, gon-escalante approved these changes

2018-08-08 19:30 UTC, merged