Footer
wolox-training/tr-react pull request #2
Opened 2018-08-08 20:41 UTC by tsregit

## Description
 - Add source with navbar.
 - Add source with footer.

## Screenshot
![image](https://user-images.githubusercontent.com/22084653/43863180-e54c83c8-9b29-11e8-8124-0883c4759e65.png)

2018-08-08 21:02 UTC, arconejeros commented on index.html
> +<div class="container-footer p-top-3">
check the identation here

2018-08-08 21:03 UTC, arconejeros commented on scss/footer.scss
> +}
add an empty line after this

2018-08-08 21:04 UTC, arconejeros commented on scss/navbar.scss
> +  z-index: 1000;
i think with one or two is sufficient

2018-08-08 21:07 UTC, arconejeros commented on index.html
>          <div class="tech">
check the identation

2018-08-08 21:09 UTC, arconejeros commented on scss/navbar.scss
> +  background-color: #FFF;
use scss variables

2018-08-08 21:10 UTC, arconejeros commented on scss/styles.scss
> +}
an empty line should be at the end of every files

2018-08-08 22:26 UTC, tsregit commented on scss/footer.scss
> +}
the change it is not reflected.

2018-08-10 17:28 UTC, gon-escalante requested changes

2018-08-10 17:28 UTC, gon-escalante commented on scss/footer.scss
> +  background-color: #00ADEE;
move this to `colors.scss`

2018-08-10 17:28 UTC, gon-escalante commented on scss/navbar.scss
> +  -webkit-box-shadow: 0 7px 30px -5px rgba(0, 0, 0, 0.30);
id also move this `rgba(0, 0, 0, 0.30)` to `colors.scss`

2018-08-10 20:09 UTC, gon-escalante approved these changes

2018-08-13 17:45 UTC, merged